[tool.black]
line-length = 88
target-version = ["py38", "py39", "py310", "py311", "py312"]
include = "\\.pyi?$"
exclude = [
  "build/",
  "dist/",
  "\.venv/",
  "\.mypy_cache/",
  "\.pytest_cache/"
]

[tool.isort]
profile = "black"
line_length = 88
combine_as_imports = true
force_sort_within_sections = true

[tool.ruff]
line-length = 88
src = ["ml-services"]
extend-exclude = [
  ".venv",
  "build",
  "dist"
]

[tool.ruff.lint]
select = [
  "E",  # pycodestyle errors
  "F",  # pyflakes
  "W",  # pycodestyle warnings
  "I",  # isort
  "B",  # flake8-bugbear
  "UP"  # pyupgrade
]
ignore = [
  "E203", # whitespace before ':' (Black-compatible)
  "E266"  # too many leading '#' for block comment
]

[tool.ruff.format]
quote-style = "preserve"
indent-style = "space"
line-ending = "lf"
