name: Build and Test - Java 21

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  build-test:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Validate project
        run: |
          cd java-backend
          ./mvnw validate

      - name: Compile project
        run: |
          cd java-backend
          ./mvnw clean compile

      - name: Run tests
        run: |
          cd java-backend
          ./mvnw test

      - name: Package project
        run: |
          cd java-backend
          ./mvnw package -DskipTests

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: java-artifacts
          path: |
            java-backend/shared-common/target/*.jar
            java-backend/target/*.jar
          retention-days: 5

  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest
    needs: build-test
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Run Checkstyle (if config exists)
        run: |
          cd java-backend
          if [ -f checkstyle.xml ]; then
            ./mvnw checkstyle:check
          else
            echo "Checkstyle configuration not found, skipping..."
          fi
        continue-on-error: true

      - name: Run SpotBugs (if configured)
        run: |
          cd java-backend
          ./mvnw spotbugs:check
        continue-on-error: true

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: build-test
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Run OWASP Dependency Check
        run: |
          cd java-backend
          ./mvnw org.owasp:dependency-check-maven:check
        continue-on-error: true

      - name: Upload OWASP report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: owasp-dependency-check-report
          path: java-backend/target/dependency-check-report.html
          retention-days: 5