name: Java Backend CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 1' # Weekly Monday 03:00 UTC

permissions:
  contents: read

concurrency:
  group: java-backend-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ACT: ${{ github.actor == 'nektos/act' }}
    defaults:
      run:
        working-directory: java-backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        if: ${{ github.actor != 'nektos/act' }}
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: 'maven'
      - name: Install JDK 17 (for local act)
        if: ${{ github.actor == 'nektos/act' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk
          java -version
      - name: Install Maven (for local act)
        if: ${{ github.actor == 'nektos/act' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y maven
      - name: Validate and compile (skip tests)
        run: mvn -B -q -DskipTests -f shared-common/pom.xml clean verify
      - name: Run unit tests
        run: mvn -B -f shared-common/pom.xml test
